"""empty message

Revision ID: 9bc3d9e6dc7c
Revises: 5ff1a02cf142
Create Date: 2022-03-23 08:50:42.105884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc3d9e6dc7c'
down_revision = '5ff1a02cf142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
